sulu/SuluContentBundle

- Controller/AbstractContentController.php
- Controller/AbstractExcerptController.php
- Controller/AbstractSeoController.php
- Resources/config/serializer/Content.ContentView.xml
- Resources/config/serializer/Excerpt.ExcerptView.xml
- Resources/config/serializer/Seo.SeoView.xml
- Tests/Application/Controller/TestControllerCallbackInterface.php
- Tests/Application/Controller/TestResourceContentController.php
- Tests/Application/Controller/TestResourceExcerptController.php
- Tests/Application/Controller/TestResourceSeoController.php
- Tests/Functional/Controller/AbstractContentControllerTest.php
- Tests/Functional/Controller/AbstractExcerptControllerTest.php
- Tests/Functional/Controller/AbstractSeoControllerTest.php
Builds upon: https://github.com/sulu/SuluContentBundle/pull/11
> Add handle-remove callback to abstract controllers

- Model/Content/ContentView.php
- Model/Seo/SeoView.php
The exception is happening when a newly created embedable is loaded from the database and the data was not set by doctrine.
> Fix exception when data is null

- Content/Domain/Model/ContentDimensionInterface.php
- Content/Domain/Model/ContentDimensionTrait.php
- Dimension/Infrastructure/Doctrine/DimensionRepository.php
- Tests/Application/ExampleTestBundle/Entity/Example.php
- Tests/Functional/Integration/ExampleControllerTest.php
- Tests/Functional/Integration/responses/example_cget.json
- Tests/Functional/Integration/responses/example_get.json
- Tests/Functional/Integration/responses/example_post.json
- Tests/Functional/Integration/responses/example_put.json
This adds a test for the ExampleController and fix create if no dimension exist.
> Add integration test and fix create dimension

- .php_cs.dist
- Content/Application/ContentDimensionFactory/ContentDimensionCollectionFactory.php
- Content/Application/MessageHandler/LoadContentMessageHandler.php
- Content/Application/MessageHandler/SaveContentMessageHandler.php
- Content/Domain/Factory/ContentDimensionCollectionFactoryInterface.php
- Content/Domain/Factory/DimensionCollectionFactory.php
- Content/Domain/Factory/DimensionCollectionFactoryInterface.php
- Content/Domain/Model/ContentViewInterface.php
- Content/Domain/Model/Dimension.php
- Content/Domain/Model/DimensionCollection.php
- Content/Domain/Model/DimensionCollectionInterface.php
- Content/Domain/Model/DimensionInterface.php
- Content/Domain/Repository/DimensionRepositoryInterface.php
- Content/Infrastructure/Doctrine/DimensionRepository.php
- Content/Infrastructure/Doctrine/MetadataLoader.php
- DependencyInjection/Configuration.php
- DependencyInjection/SuluContentExtension.php
- Resources/config/doctrine/Dimension/Dimension.orm.xml
- Resources/config/services.xml
- SuluContentBundle.php
- TestCases/Dimension/DimensionRepositoryTestCaseTrait.php
- Tests/Functional/Content/Infrastructure/Doctrine/DimensionRepositoryTest.php
- Tests/Functional/Integration/ExampleControllerTest.php
- Tests/Unit/Content/Application/ContentDimensionFactory/ContentDimensionCollectionFactoryTest.php
- Tests/Unit/Content/Application/MessageHandler/LoadContentMessageHandlerTest.php
- Tests/Unit/Content/Application/MessageHandler/SaveContentMessageHandlerTest.php
- Tests/Unit/Content/Domain/Factory/DimensionFactoryTest.php
- Tests/Unit/Content/Domain/Model/DimensionCollectionTest.php
- Tests/Unit/Content/Domain/Model/DimensionTest.php
- Tests/Unit/DependencyInjection/SuluContentExtensionTest.php
The Content shoud be able to access properties of the Dimension so we need to move the Dimension into the Content namespace
> Move dimension namespace into content namespace

- Content/Infrastructure/Doctrine/MetadataLoader.php
- Tests/Application/ExampleTestBundle/Controller/ExampleController.php
- Tests/Application/ExampleTestBundle/Resources/config/lists/examples.xml
- Tests/Functional/Integration/ExampleControllerTest.php
- Tests/Functional/Integration/responses/example_cget.json
This is just a basic implementation how to  show the title on a list.
> Add title to list

- .prettyci.composer.json
- Content/Application/ContentDimensionFactory/ContentDimensionCollectionFactory.php
- Content/Application/ContentDimensionFactory/Mapper/ExcerptMapper.php
- Content/Application/ContentDimensionFactory/Mapper/RouteMapper.php
- Content/Application/ContentDimensionFactory/Mapper/SeoMapper.php
- Content/Application/ContentDimensionFactory/Mapper/TemplateMapper.php
- Tests/Unit/Content/Infrastructure/Doctrine/MetadataLoaderTest.php
UPGRADE pretty ci to newest php-cs-fixer
> Upgrade pretty ci php-cs-fixer

- Content/Application/ContentDimensionFactory/ContentDimensionCollectionFactory.php
- Content/Application/MessageHandler/LoadContentMessageHandler.php
- Content/Application/MessageHandler/LoadContentViewMessageHandler.php
- Content/Domain/Repository/ContentDimensionRepositoryInterface.php
- Content/Infrastructure/Doctrine/ContentDimensionRepository.php
- Resources/config/handlers.xml
- Resources/config/services.xml
- Tests/Functional/Content/Infrastructure/Doctrine/ContentDimensionRepositoryTest.php
- Tests/Unit/Content/Application/ContentDimensionFactory/ContentDimensionCollectionFactoryTest.php
- Tests/Unit/Content/Application/MessageHandler/LoadContentMessageHandlerTest.php
- Tests/Unit/Content/Application/MessageHandler/LoadContentViewMessageHandlerTest.php
- phpunit.xml.dist
As discussed with @wachterjohannes and @nnatter we rename the ContentDimensionLoader to ContentDimensionRepository.
> Rename ContentDimensionLoader to ContentDimensionRepository

- Resources/config/services.xml
- Tests/Unit/DependencyInjection/SuluContentExtensionTest.php
Add alias for content_facade service.
> Add autowire for the ContentFacadeInterface

- .gitignore
- composer.json
- depfile.yml
To validate which classes are allowed to access other classes.
> Add deptract configuration for content

- Tests/Application/ExampleTestBundle/Admin/ExampleAdmin.php
- Tests/Application/ExampleTestBundle/DependencyInjection/ExampleTestExtension.php
- Tests/Application/ExampleTestBundle/Entity/Example.php
- Tests/Application/ExampleTestBundle/Entity/ExampleDimension.php
- Tests/Application/ExampleTestBundle/Entity/ExampleView.php
> Rename example const TYPE_KEY to TEMPLATE_TYPE

- Content/Application/ContentCopier/ContentCopier.php
- Content/Application/ContentFacade/ContentFacade.php
- Content/Application/ContentFacade/ContentFacadeInterface.php
- Content/Application/ContentResolver/ContentResolver.php
- Content/Application/ContentResolver/ContentResolverInterface.php
- Content/Infrastructure/Sulu/Route/ContentRouteDefaultsProvider.php
- Resources/config/services.xml
- Tests/Application/ExampleTestBundle/Controller/ExampleController.php
- Tests/Unit/Content/Application/ContentCopier/ContentCopierTest.php
- Tests/Unit/Content/Application/ContentFacade/ContentFacadeTest.php
- Tests/Unit/Content/Application/ContentResolver/ContentResolverTest.php
- Tests/Unit/Content/Infrastructure/Sulu/Route/ContentRouteDefaultsProviderTest.php
- Tests/Unit/DependencyInjection/SuluContentExtensionTest.php
parts of #52 
build on top of #64
> Rename ContentLoader to ContentResolver

- Content/Application/DimensionContentFactory/DataMapper/DataMapperInterface.php
- Content/Application/DimensionContentFactory/DataMapper/ExcerptDataMapper.php
- Content/Application/DimensionContentFactory/DataMapper/RouteDataMapper.php
- Content/Application/DimensionContentFactory/DataMapper/SeoDataMapper.php
- Content/Application/DimensionContentFactory/DataMapper/TemplateDataMapper.php
- Content/Application/DimensionContentFactory/DimensionContentCollectionFactory.php
- Resources/config/mapper.xml
- Resources/config/services.xml
- Tests/Unit/Content/Application/DimensionContentFactory/DataMapper/ExcerptMapperTest.php
- Tests/Unit/Content/Application/DimensionContentFactory/DataMapper/RouteMapperTest.php
- Tests/Unit/Content/Application/DimensionContentFactory/DataMapper/SeoMapperTest.php
- Tests/Unit/Content/Application/DimensionContentFactory/DataMapper/TemplateMapperTest.php
- Tests/Unit/Content/Application/DimensionContentFactory/DimensionContentCollectionFactoryTest.php
parts of #52 
build on top of #66
> Rename Mapper to DataMapper

- Content/Application/ContentManager/ContentManager.php
- Content/Application/ContentManager/ContentManagerInterface.php
- Resources/config/services.xml
- Tests/Application/ExampleTestBundle/Controller/ExampleController.php
- Tests/Application/ExampleTestBundle/Resources/config/services.yaml
- Tests/Unit/Content/Application/ContentManager/ContentManagerTest.php
- Tests/Unit/DependencyInjection/SuluContentExtensionTest.php
parts of #52 
build on top of #67
> Rename ContentFacade to ContentManager

- Content/Infrastructure/Sulu/Admin/ContentViewBuilder.php
- Tests/Application/ExampleTestBundle/Resources/views/base.html.twig
- composer.json
This will hide the save and delete button if the user has no permissions for it and the api does provide it.
> Add display conditions to toolbar actions

- Content/Infrastructure/Sulu/Admin/ContentViewBuilder.php
See https://github.com/sulu/sulu/pull/5007
> Fix disabled condition

- Content/Application/DimensionCollectionFactory/DimensionCollectionFactory.php
- Content/Application/DimensionContentCollectionFactory/DataMapper/DataMapperInterface.php
- Content/Application/DimensionContentCollectionFactory/DataMapper/ExcerptDataMapper.php
- Content/Application/DimensionContentCollectionFactory/DataMapper/RouteDataMapper.php
- Content/Application/DimensionContentCollectionFactory/DataMapper/SeoDataMapper.php
- Content/Application/DimensionContentCollectionFactory/DataMapper/TemplateDataMapper.php
- Content/Application/DimensionContentCollectionFactory/DimensionContentCollectionFactory.php
- Content/Infrastructure/Doctrine/DimensionContentRepository.php
- Resources/config/mapper.xml
- Resources/config/services.xml
- Tests/Unit/Content/Application/DimensionCollectionFactory/DimensionCollectionFactoryTest.php
- Tests/Unit/Content/Application/DimensionContentCollectionFactory/DataMapper/ExcerptMapperTest.php
- Tests/Unit/Content/Application/DimensionContentCollectionFactory/DataMapper/RouteMapperTest.php
- Tests/Unit/Content/Application/DimensionContentCollectionFactory/DataMapper/SeoMapperTest.php
- Tests/Unit/Content/Application/DimensionContentCollectionFactory/DataMapper/TemplateMapperTest.php
- Tests/Unit/Content/Application/DimensionContentCollectionFactory/DimensionContentCollectionFactoryTest.php
* Rename DimensionContentFactory namespace to DimensionContentCollectionFactory
* Move DimensionCollectionFactory implementation into Application namespace
> Fix naming inconsistencies

- Content/Application/DimensionContentCollectionFactory/DataMapper/RoutableDataMapper.php
- Content/Application/DimensionContentCollectionFactory/DataMapper/TemplateDataMapper.php
- Content/Domain/Model/TemplateInterface.php
- Content/Infrastructure/Sulu/Route/ContentRouteDefaultsProvider.php
- Tests/Application/ExampleTestBundle/Entity/ExampleContentProjection.php
- Tests/Application/ExampleTestBundle/Entity/ExampleDimensionContent.php
- Tests/Unit/Content/Application/ContentNormalizer/ContentNormalizerTest.php
- Tests/Unit/Content/Application/DimensionContentCollectionFactory/DataMapper/RoutableDataMapperTest.php
- Tests/Unit/Content/Application/DimensionContentCollectionFactory/DataMapper/TemplateDataMapperTest.php
- Tests/Unit/Content/Domain/Model/ContentRichEntityTest.php
- Tests/Unit/Content/Domain/Model/TemplateTraitTest.php
- Tests/Unit/Content/Infrastructure/Sulu/Preview/ContentObjectProviderTest.php
- Tests/Unit/Content/Infrastructure/Sulu/Route/ContentRouteDefaultsProviderTest.php
- Tests/Unit/Mocks/ContentProjectionMockWrapperTrait.php
- Tests/Unit/Mocks/MockWrapper.php
- Tests/Unit/Mocks/RoutableMockWrapperTrait.php
- Tests/Unit/Mocks/TemplateMockWrapperTrait.php
> Declare getTemplateType method on TemplateInterface as static

- Content/Application/ContentDataMapper/ContentDataMapper.php
- Content/Application/ContentDataMapper/ContentDataMapperInterface.php
- Content/Application/ContentDataMapper/DataMapper/DataMapperInterface.php
- Content/Application/ContentDataMapper/DataMapper/ExcerptDataMapper.php
- Content/Application/ContentDataMapper/DataMapper/RoutableDataMapper.php
- Content/Application/ContentDataMapper/DataMapper/SeoDataMapper.php
- Content/Application/ContentDataMapper/DataMapper/TemplateDataMapper.php
- Content/Application/DimensionContentCollectionFactory/DimensionContentCollectionFactory.php
- DependencyInjection/SuluContentExtension.php
- Resources/config/data-mapper.xml
- Resources/config/services.xml
- Tests/Unit/Content/Application/ContentDataMapper/ContentDataMapperTest.php
- Tests/Unit/Content/Application/ContentDataMapper/DataMapper/ExcerptDataMapperTest.php
- Tests/Unit/Content/Application/ContentDataMapper/DataMapper/RoutableDataMapperTest.php
- Tests/Unit/Content/Application/ContentDataMapper/DataMapper/SeoDataMapperTest.php
- Tests/Unit/Content/Application/ContentDataMapper/DataMapper/TemplateDataMapperTest.php
- Tests/Unit/Content/Application/DimensionContentCollectionFactory/DimensionContentCollectionFactoryTest.php
Fixes https://github.com/sulu/SuluContentBundle/issues/88
> Implement ContentDataMapper service

- Content/Application/ContentMerger/ContentMerger.php
- Content/Application/ContentMerger/ContentMergerInterface.php
- Content/Application/ContentMerger/Merger/ExcerptMerger.php
- Content/Application/ContentMerger/Merger/MergerInterface.php
- Content/Application/ContentMerger/Merger/SeoMerger.php
- Content/Application/ContentMerger/Merger/TemplateMerger.php
- Content/Application/ContentMerger/Merger/WorkflowMerger.php
- Content/Application/ContentProjectionFactory/ContentProjectionFactory.php
- Content/Infrastructure/Sulu/Preview/ContentObjectProvider.php
- Resources/config/merger.xml
- Resources/config/services.xml
- Tests/Unit/Content/Application/ContentMerger/ContentMergerTest.php
- Tests/Unit/Content/Application/ContentMerger/Merger/ExcerptMergerTest.php
- Tests/Unit/Content/Application/ContentMerger/Merger/SeoMergerTest.php
- Tests/Unit/Content/Application/ContentMerger/Merger/TemplateMergerTest.php
- Tests/Unit/Content/Application/ContentMerger/Merger/WorkflowMergerTest.php
- Tests/Unit/Content/Application/ContentProjectionFactory/ContentProjectionFactoryTest.php
- UPGRADE.md
Builds upon https://github.com/sulu/SuluContentBundle/pull/119
Fixes https://github.com/sulu/SuluContentBundle/issues/106
> Implement ContentMerger service

- Content/Application/ContentNormalizer/ContentNormalizer.php
- Content/Application/ContentNormalizer/Normalizer/ContentProjectionNormalizer.php
- Resources/config/normalizer.xml
- Tests/Unit/Content/Application/ContentNormalizer/ContentNormalizerTest.php
- Tests/Unit/Content/Application/ContentNormalizer/Normalizer/ContentProjectionNormalizerTest.php
Did not think about this when implementing https://github.com/sulu/SuluContentBundle/issues/107
> Move code related to ContentProjection from ContentNormalizer to ContentProjectionNormalizer

- Content/Infrastructure/Sulu/SmartContent/DataItem/ContentDataItem.php
- Content/Infrastructure/Sulu/SmartContent/Provider/ContentDataProvider.php
- Content/Infrastructure/Sulu/SmartContent/Repository/ContentDataProviderRepository.php
- Content/Infrastructure/Sulu/Teaser/ContentTeaserProvider.php
- Resources/translations/admin.de.json
- Resources/translations/admin.en.json
- Tests/Application/ExampleTestBundle/Resources/config/services.yaml
- Tests/Functional/BaseTestCase.php
- Tests/Functional/Content/Infrastructure/Sulu/SmartContent/ContentDataProviderTest.php
- Tests/Functional/Content/Infrastructure/Sulu/SmartContent/snapshots/data_items.json
- Tests/Functional/Content/Infrastructure/Sulu/SmartContent/snapshots/resource_items.json
- Tests/Traits/CreateCategoryTrait.php
- Tests/Traits/ModifyCategoryTrait.php
- Tests/Unit/Content/Infrastructure/Sulu/SmartContent/DataItem/ContentDataItemTest.php
- composer.json
This PR adds classes for SmartContent.
* Register `ContentDataProviderRepository` (or a child class of it) as service
* Register `ContentDataProvider` (or a child class of it) as service and tag it as `data provider`
> Add smart content

- Content/Application/ContentDataMapper/DataMapper/ExcerptDataMapper.php
- Content/Application/ContentDataMapper/DataMapper/SeoDataMapper.php
- Content/Application/ContentDataMapper/DataMapper/TemplateDataMapper.php
- Content/Application/ContentDataMapper/DataMapper/WorkflowDataMapper.php
- Content/Application/ContentWorkflow/Subscriber/PublishTransitionSubscriber.php
- Content/Application/ContentWorkflow/Subscriber/UnpublishTransitionSubscriber.php
- Content/Domain/Model/WorkflowTrait.php
- Resources/config/data-mapper.xml
- Tests/Functional/Integration/ExampleControllerTest.php
- Tests/Functional/Integration/responses/example_post_trigger_unpublish.json
- Tests/Unit/Content/Application/ContentDataMapper/DataMapper/TemplateDataMapperTest.php
- Tests/Unit/Content/Application/ContentDataMapper/DataMapper/WorkflowDataMapperTest.php
- Tests/Unit/Content/Application/ContentWorkflow/Subscriber/PublishTransitionSubscriberTest.php
- Tests/Unit/Content/Application/ContentWorkflow/Subscriber/UnpublishTransitionSubscriberTest.php
- Tests/Unit/Content/Domain/Model/WorkflowTraitTest.php
> Copy published date to live DimensionContent

- UPGRADE.md
Linting should be fixed with: https://github.com/sulu/sulu/pull/5293
> Update Upgrade file for Release 0.3.0

- Content/Infrastructure/Sulu/Automation/ContentPublishTaskHandler.php
- Content/Infrastructure/Sulu/Automation/ContentUnpublishTaskHandler.php
- Resources/config/automation.xml
- Tests/Unit/Content/Infrastructure/Sulu/Automation/ContentPublishTaskHandlerTest.php
- Tests/Unit/Content/Infrastructure/Sulu/Automation/ContentUnpublishTaskHandlerTest.php
- UPGRADE.md
> Move SuluAutomationBundle services into Infrastructure namespace

- Resources/config/automation.xml
- Tests/Application/Kernel.php
- composer.json
The optional AutomationBundle services should be linted in the test environment.
> Fix automation bundle service definition

- Content/Application/ContentDataMapper/DataMapper/WorkflowDataMapper.php
- Content/Application/ContentWorkflow/ContentWorkflow.php
- Content/Domain/Model/WorkflowInterface.php
- Content/Domain/Model/WorkflowTrait.php
- Content/Infrastructure/Doctrine/MetadataLoader.php
- Tests/Unit/Content/Application/ContentDataMapper/DataMapper/WorkflowDataMapperTest.php
- Tests/Unit/Content/Application/ContentNormalizer/ContentNormalizerTest.php
- Tests/Unit/Content/Domain/Model/WorkflowTraitTest.php
- Tests/Unit/Mocks/WorkflowMockWrapperTrait.php
What do you think about this solution? This would fix #92
> Set workflow place only on draft dimension

- Content/Application/ContentDataMapper/DataMapper/RoutableDataMapper.php
- Content/Domain/Model/RoutableInterface.php
- Content/Domain/Model/RoutableTrait.php
- Content/Infrastructure/Sulu/Teaser/ContentTeaserProvider.php
- Resources/config/data-mapper.xml
- Tests/Application/ExampleTestBundle/DependencyInjection/ExampleTestExtension.php
- Tests/Functional/Integration/responses/example_get.json
- Tests/Functional/Integration/responses/example_post.json
- Tests/Functional/Integration/responses/example_post_publish.json
- Tests/Functional/Integration/responses/example_post_trigger_unpublish.json
- Tests/Functional/Integration/responses/example_put.json
- Tests/Unit/Content/Application/ContentDataMapper/DataMapper/RoutableDataMapperTest.php
- Tests/Unit/Content/Application/ContentNormalizer/ContentNormalizerTest.php
- Tests/Unit/Mocks/RoutableMockWrapperTrait.php
- UPGRADE.md
Adds the possibility to configure custom routes for the content entity.
> Add configurable route-schema
